#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Roman Urdu -> Urdu script converter for Digital Family Tree UI."""
import os
import re

RAW = {
    "Kuch ghalat ho gaya. Dobara koshish karein.": "کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔",
    "Maazrat ke saath, technical masla aa gaya hai. Dobara koshish karein.": "معذرت کے ساتھ، تکنیکی مسئلہ آ گیا ہے۔ دوبارہ کوشش کریں۔",
    "Kuch ghalat ho gaya": "کچھ غلط ہو گیا",
    "Dobara Koshish Karein": "دوبارہ کوشش کریں",
    "Network error. Dobara koshish karein.": "نیٹ ورک کی خرابی۔ دوبارہ کوشش کریں۔",
    "Bohat zyada koshishein. 15 minute baad dobara koshish karein": "بہت زیادہ کوششیں۔ 15 منٹ بعد دوبارہ کوشش کریں",
    "Bohat zyada koshishein. Thori der baad dobara koshish karein": "بہت زیادہ کوششیں۔ تھوڑی دیر بعد دوبارہ کوشش کریں",
    "Koi data nahi mila": "کوئی ڈیٹا نہیں ملا",
    "Koi notification nahi hai 🔔": "کوئی اطلاع نہیں ہے 🔔",
    "Abhi yahan kuch nahi hai.": "ابھی یہاں کچھ نہیں ہے۔",
    "Koi nahi": "کوئی نہیں",
    "Filhal nahi": "فی الحال نہیں",
    "Kabhi nahi": "کبھی نہیں",
    "Nahi hai": "نہیں ہے",
    "Nahi bataya gaya": "نہیں بتایا گیا",
    "Nahi batayi gayin": "نہیں بتائی گئیں",
    "Abhi nahi banaya": "ابھی نہیں بنایا",
    "Abhi kisi clan se judein nahi": "ابھی کسی کلان سے نہیں جڑے",
    "Koi bio nahi hai": "کوئی تعارف نہیں ہے",
    "Koi description nahi hai.": "کوئی تفصیل نہیں ہے۔",
    "Koi taaruf nahi likha gaya": "کوئی تعارف نہیں لکھا گیا",
    "Koi community nahi mili": "کوئی کمیونٹی نہیں ملی",
    "Age nahi batayi": "عمر نہیں بتائی",
    "Deactivate hai": "غیر فعال ہے",
    "Active hai ✓": "فعال ہے ✓",
    "Bana hua hai ✓": "بنا ہوا ہے ✓",
    "Koi bhi": "کوئی بھی",
    "Sab types": "تمام اقسام",
    "Sab categories": "تمام زمرے",
    "Sab industries": "تمام صنعتیں",
    "Sab roles": "تمام کردار",
    "Sab statuses": "تمام حالتیں",
    "Sab Dekhein": "سب دیکھیں",
    "Sab Profiles Dekhein": "تمام پروفائلز دیکھیں",
    "Dekhein": "دیکھیں",
    "Chunein": "منتخب کریں",
    "Banayein": "بنائیں",
    "Profiles Dekhein": "پروفائلز دیکھیں",
    "Profiles load nahi ho sakin": "پروفائلز لوڈ نہیں ہو سکیں",
    "Requests load nahi hui": "درخواستیں لوڈ نہیں ہوئیں",
    "Settings load nahi ho sakin": "سیٹنگز لوڈ نہیں ہو سکیں",
    "Data load nahi ho saka": "ڈیٹا لوڈ نہیں ہو سکا",
    "Dashboard data load nahi ho saka": "ڈیش بورڈ ڈیٹا لوڈ نہیں ہو سکا",
    "Event load nahi ho saka": "ایونٹ لوڈ نہیں ہو سکا",
    "Events load nahi ho sake": "ایونٹس لوڈ نہیں ہو سکے",
    "Memories load nahi ho sakin": "یادیں لوڈ نہیں ہو سکیں",
    "Media load nahi ho saka": "میڈیا لوڈ نہیں ہو سکا",
    "Jobs load nahi ho sakin": "نوکریاں لوڈ نہیں ہو سکیں",
    "Job load nahi ho saki": "نوکری لوڈ نہیں ہو سکی",
    "Business load nahi ho saka": "بزنس لوڈ نہیں ہو سکا",
    "Businesses load nahi ho sake": "بزنسز لوڈ نہیں ہو سکے",
    "Clan data load nahi ho saka": "کلان ڈیٹا لوڈ نہیں ہو سکا",
    "Community data load nahi ho saka": "کمیونٹی ڈیٹا لوڈ نہیں ہو سکا",
    "Notifications load nahi ho sakin": "اطلاعات لوڈ نہیں ہو سکیں",
    "Reports load nahi ho sakin": "رپورٹس لوڈ نہیں ہو سکیں",
    "Audit log load nahi ho saka": "آڈٹ لاگ لوڈ نہیں ہو سکا",
    "Messages load nahi ho sake": "پیغامات لوڈ نہیں ہو سکے",
    "Details load nahi ho sakin": "تفصیلات لوڈ نہیں ہو سکیں",
    "Job profile load nahi hui": "جاب پروفائل لوڈ نہیں ہوئی",
    "Profile load nahi ho saki": "پروفائل لوڈ نہیں ہو سکی",
    "Job profile save nahi hui": "جاب پروفائل محفوظ نہیں ہوئی",
    "Profile save nahi ho saki": "پروفائل محفوظ نہیں ہو سکی",
    "Profile photo set nahi ho saki": "پروفائل فوٹو سیٹ نہیں ہو سکی",
    "Save Karein": "محفوظ کریں",
    "Save ho raha hai...": "محفوظ ہو رہا ہے...",
    "Save nahi ho saka": "محفوظ نہیں ہو سکا",
    "Changes Save Karein": "تبدیلیاں محفوظ کریں",
    "Password Save Karein": "پاس ورڈ محفوظ کریں",
    "Profile Save Karein": "پروفائل محفوظ کریں",
    "Memory Save Karein": "یاد محفوظ کریں",
    "Update ho gaya!": "اپ ڈیٹ ہو گیا!",
    "Update ho raha hai...": "اپ ڈیٹ ہو رہا ہے...",
    "Update nahi ho saka": "اپ ڈیٹ نہیں ہو سکا",
    "Delete ho gaya": "ڈیلیٹ ہو گیا",
    "Delete nahi ho saka": "ڈیلیٹ نہیں ہو سکا",
    "Delete nahi ho saki": "ڈیلیٹ نہیں ہو سکی",
    "Create ho gaya!": "بنا دیا گیا!",
    "Create nahi ho saka": "بنایا نہیں جا سکا",
    "Action kamyab raha": "کارروائی کامیاب رہی",
    "Action nahi ho saka": "کارروائی نہیں ہو سکی",
    "Edit Karein": "ترمیم کریں",
    "Event Edit Karein": "ایونٹ میں ترمیم کریں",
    "Ghalat action": "غلط کارروائی",
    "Ghalat entity": "غلط اندراج",
    "Ghalat request": "غلط درخواست",
    "Yeh action wapas nahi ho sakta.": "یہ کارروائی واپس نہیں ہو سکتی۔",
    "Kuch record nahi hua": "کچھ ریکارڈ نہیں ہوا",
    "Link copy ho gaya!": "لنک کاپی ہو گیا!",
    "Location search karein...": "مقام تلاش کریں...",
    "Naam ya city se dhundein...": "نام یا شہر سے تلاش کریں...",
    "Maybe mark ho gaya": "شاید نشان زد ہو گیا",
    "Load ho raha hai...": "لوڈ ہو رہا ہے...",
    "Bheja ja raha hai...": "بھیجا جا رہا ہے...",
    "Upload ho raha hai...": "اپ لوڈ ہو رہا ہے...",
    "Upload nahi ho saka": "اپ لوڈ نہیں ہو سکا",
    "Upload mein masla aa gaya": "اپ لوڈ میں مسئلہ آ گیا",
    "Post ho rahi hai...": "پوسٹ ہو رہی ہے...",
    "Login Karein": "لاگ اِن کریں",
    "Login ho raha hai...": "لاگ اِن ہو رہا ہے...",
    "Login nahi ho saka": "لاگ اِن نہیں ہو سکا",
    "Login karna zaroori hai": "لاگ اِن کرنا ضروری ہے",
    "Email aur password dono likhein": "ای میل اور پاس ورڈ دونوں لکھیں",
    "Email ya password ghalat hai": "ای میل یا پاس ورڈ غلط ہے",
    "Khush aamdeed! Login kamyab.": "خوش آمدید! لاگ اِن کامیاب۔",
    "Register Karein": "رجسٹر کریں",
    "Register ho raha hai...": "رجسٹر ہو رہا ہے...",
    "Registration nahi ho saki": "رجسٹریشن نہیں ہو سکی",
    "Account ban gaya! Ab login karein.": "اکاؤنٹ بن گیا! اب لاگ اِن کریں۔",
    "Account ban gaya! Login karein.": "اکاؤنٹ بن گیا! لاگ اِن کریں۔",
    "Account ban raha hai...": "اکاؤنٹ بن رہا ہے...",
    "Sirf 2 minute mein free account banayein. Google se bhi sign up kar sakte hain.": "صرف 2 منٹ میں فری اکاؤنٹ بنائیں۔ گوگل سے بھی سائن اپ کر سکتے ہیں۔",
    "Google login nahi ho saka. (Google OAuth credentials configure karein)": "گوگل لاگ اِن نہیں ہو سکا۔ (گوگل OAuth کریڈینشلز کنفیگر کریں)",
    "Google login walay users ka password nahi hota": "گوگل لاگ اِن والے صارفین کا پاس ورڈ نہیں ہوتا",
    "Reset Link Bhejein": "ری سیٹ لنک بھیجیں",
    "Agar email mojood hai to reset link bhej diya gaya hai. Email check karein.": "اگر ای میل موجود ہے تو ری سیٹ لنک بھیج دیا گیا ہے۔ ای میل چیک کریں۔",
    "Reset link bhej diya gaya hai": "ری سیٹ لنک بھیج دیا گیا ہے",
    "Reset link ghalat hai": "ری سیٹ لنک غلط ہے",
    "Reset link expire ho gaya hai ya ghalat hai": "ری سیٹ لنک کی مدت ختم ہو گئی ہے یا لنک غلط ہے",
    "Email bhejne mein masla aa gaya. Dobara koshish karein.": "ای میل بھیجنے میں مسئلہ آ گیا۔ دوبارہ کوشش کریں۔",
    "Dono passwords match nahi karte": "دونوں پاس ورڈز مماثل نہیں ہیں",
    "Password badal gaya! Ab login karein.": "پاس ورڈ بدل گیا! اب لاگ اِن کریں۔",
    "Password badal gaya!": "پاس ورڈ بدل گیا!",
    "Password nahi badla": "پاس ورڈ نہیں بدلا",
    "Password reset nahi ho saka": "پاس ورڈ ری سیٹ نہیں ہو سکا",
    "Password ghalat hai (hint: family123)": "پاس ورڈ غلط ہے (اشارہ: family123)",
    "Password ghalat hai": "پاس ورڈ غلط ہے",
    "Password likhein": "پاس ورڈ لکھیں",
    "Maujuda password ghalat hai": "موجودہ پاس ورڈ غلط ہے",
    "Maujuda password likhein": "موجودہ پاس ورڈ لکھیں",
    "Apna password (confirm ke liye)": "اپنا پاس ورڈ (تصدیق کے لیے)",
    "Password mein ek English harf zaroori hai": "پاس ورڈ میں ایک انگریزی حرف ضروری ہے",
    "Password mein ek number zaroori hai": "پاس ورڈ میں ایک نمبر ضروری ہے",
    "Sahi email address likhein": "درست ای میل ایڈریس لکھیں",
    "Sahi email likhein": "درست ای میل لکھیں",
    "Ye email pehle se registered hai": "یہ ای میل پہلے سے رجسٹرڈ ہے",
    "Yeh email pehle se register hai": "یہ ای میل پہلے سے رجسٹرڈ ہے",
    "Sahi Pakistani mobile number likhein (03001234567)": "درست پاکستانی موبائل نمبر لکھیں (03001234567)",
    "Sahi Pakistani mobile number likhein": "درست پاکستانی موبائل نمبر لکھیں",
    "Sahi Pakistani number likhein (03001234567)": "درست پاکستانی نمبر لکھیں (03001234567)",
    "Ye phone number pehle se registered hai": "یہ فون نمبر پہلے سے رجسٹرڈ ہے",
    "Yeh phone number pehle se register hai": "یہ فون نمبر پہلے سے رجسٹرڈ ہے",
    "Yeh phone number kisi aur ka hai": "یہ فون نمبر کسی اور کا ہے",
    "Aapka poora naam": "آپ کا پورا نام",
    "Aapka naam": "آپ کا نام",
    "Naam likhein": "نام لکھیں",
    "Naam kam az kam 2 huroof ka hona chahiye": "نام کم از کم 2 حروف کا ہونا چاہیے",
    "Aapka account ban kar diya gaya hai": "آپ کا اکاؤنٹ بند کر دیا گیا ہے",
    "Aapka account deactivate hai": "آپ کا اکاؤنٹ غیر فعال ہے",
    "Event Banayein": "ایونٹ بنائیں",
    "Events Banayein": "ایونٹس بنائیں",
    "Events Banaye": "بنائے گئے ایونٹس",
    "Clan Members": "کلان ممبران",
    "Memories Saved": "محفوظ یادیں",
    "Unread Notifications": "غیر پڑھی اطلاعیں",
    "Profile Dekhein": "پروفائل دیکھیں",
    "Event banaya: ": "ایونٹ بنایا: ",
    "Memory save ki: ": "یاد محفوظ کی: ",
    "Media upload kiya": "میڈیا اپ لوڈ کیا",
    "Naya Event Banayein": "نیا ایونٹ بنائیں",
    "Event ban gaya! 🎉": "ایونٹ بن گیا! 🎉",
    "Event ban raha hai...": "ایونٹ بن رہا ہے...",
    "Event nahi ban saka": "ایونٹ نہیں بن سکا",
    "Event nahi mila": "ایونٹ نہیں ملا",
    "Event delete ho gaya": "ایونٹ ڈیلیٹ ہو گیا",
    "Event update ho gaya ✅": "ایونٹ اپ ڈیٹ ہو گیا ✅",
    "Event update nahi ho saka": "ایونٹ اپ ڈیٹ نہیں ہو سکا",
    "Event id zaroori hai": "ایونٹ آئی ڈی ضروری ہے",
    "Event ke baare mein likhein — kya hoga, kya layein, etc.": "ایونٹ کے بارے میں لکھیں — کیا ہوگا، کیا لائیں، وغیرہ۔",
    "Event ki details update karke save karein": "ایونٹ کی تفصیلات اپ ڈیٹ کر کے محفوظ کریں",
    "Family events banayein, dekhein aur RSVP karein": "فیملی ایونٹس بنائیں، دیکھیں اور RSVP کریں",
    "Family events banayein, manage karein aur RSVP lein — shaadi, eid, mehndi sab.": "فیملی ایونٹس بنائیں، منظم کریں اور RSVP لیں — شادی، عید، مہندی سب۔",
    "Shaadi, eid, aqeeqa — koi bhi event banayein aur family ko invite karein.": "شادی، عید، عقیقہ — کوئی بھی ایونٹ بنائیں اور فیملی کو مدعو کریں۔",
    "Abhi koi event nahi hai. Pehla event banayein!": "ابھی کوئی ایونٹ نہیں ہے۔ پہلا ایونٹ بنائیں!",
    "Event reminders, rishta requests aur updates — kabhi miss na karein.": "ایونٹ ریمائنڈرز، رشتہ کی درخواستیں اور اپ ڈیٹس — کبھی مس نہ کریں۔",
    "Theek hai, aap nahi aa rahe": "ٹھیک ہے، آپ نہیں آ رہے",
    "Shukriya! Aap ja rahe hain 🎉": "شکریہ! آپ جا رہے ہیں 🎉",
    "RSVP save nahi ho saka": "RSVP محفوظ نہیں ہو سکا",
    "Date chunein": "تاریخ منتخب کریں",
    "Clan Se Judein": "کلان سے جڑیں",
    "Clan chunein": "کلان منتخب کریں",
    "Community chunein": "کمیونٹی منتخب کریں",
    "Sub-clan chunein": "سب کلان منتخب کریں",
    "Clans Browse Karein": "کلانز براؤز کریں",
    "Join request bhej di gayi! Approval ke baad aap member ban jayenge.": "شمولیت کی درخواست بھیج دی گئی! منظوری کے بعد آپ ممبر بن جائیں گے۔",
    "Aap pehle se is clan ke member hain": "آپ پہلے سے اس کلان کے ممبر ہیں",
    "Aap pehle se request bhej chuke hain": "آپ پہلے سے درخواست بھیج چکے ہیں",
    "Aapki request pehle se pending hai": "آپ کی درخواست پہلے سے زیر التوا ہے",
    "Aapko is action ki ijazat nahi hai": "آپ کو اس کارروائی کی اجازت نہیں ہے",
    "Abhi koi clan nahi hai. Admin se raabta karein.": "ابھی کوئی کلان نہیں ہے۔ ایڈمن سے رابطہ کریں۔",
    "Apni community aur clan chunein. Apne logon ko dhundein aur judein.": "اپنی کمیونٹی اور کلان منتخب کریں۔ اپنے لوگوں کو ڈھونڈیں اور جڑیں۔",
    "Apni community, clan aur sub-clan se judein. Apne logon ko dhundein.": "اپنی کمیونٹی، کلان اور سب کلان سے جڑیں۔ اپنے لوگوں کو ڈھونڈیں۔",
    "Community ya clan dhundein...": "کمیونٹی یا کلان تلاش کریں...",
    "Is community mein clans mojood hain, pehle unhein delete karein": "اس کمیونٹی میں کلانز موجود ہیں، پہلے انہیں ڈیلیٹ کریں",
    "Is clan mein sub-clans mojood hain, pehle unhein delete karein": "اس کلان میں سب کلانز موجود ہیں، پہلے انہیں ڈیلیٹ کریں",
    "Unfollow ho gaya": "ان فالو ہو گیا",
    "Follow Karein": "فالو کریں",
    "Aap abhi kisi clan ke member nahi hain. Neeche clans browse karein aur join karein!": "آپ ابھی کسی کلان کے ممبر نہیں ہیں۔ نیچے کلانز براؤز کریں اور جوائن کریں!",
    "Rishta Dekhein": "رشتہ دیکھیں",
    "Rishta Request": "رشتہ کی درخواست",
    "Rishta requests": "رشتہ کی درخواستیں",
    "Rishta Profile Banayein": "رشتہ پروفائل بنائیں",
    "Rishta Profile": "رشتہ پروفائل",
    "Rishta Profiles": "رشتہ پروفائلز",
    "Rishta Accepted": "رشتہ منظور",
    "Rishta profile ban gaya! 💚": "رشتہ پروفائل بن گیا! 💚",
    "Rishta profile deactivate ho gaya": "رشتہ پروفائل غیر فعال ہو گیا",
    "Rishta request accept!": "رشتہ کی درخواست منظور!",
    "Rishta request qabool ho gayi! 🎉": "رشتہ کی درخواست قبول ہو گئی! 🎉",
    "Rishta request par jawab": "رشتہ کی درخواست پر جواب",
    "Nayi rishta request!": "نئی رشتہ کی درخواست!",
    "Aapki rishta request accept kar li gayi hai": "آپ کی رشتہ کی درخواست قبول کر لی گئی ہے",
    "Abhi aapko koi rishta request nahi aayi. Apna profile active rakhein.": "ابھی آپ کو کوئی رشتہ کی درخواست نہیں آئی۔ اپنا پروفائل فعال رکھیں۔",
    "Pehle apna rishta profile banayein": "پہلے اپنا رشتہ پروفائل بنائیں",
    "Aap kaisa rishta chahte hain?": "آپ کیسا رشتہ چاہتے ہیں؟",
    "Respectful aur safe tareeqe se rishta dhundein": "احترام اور حفاظت کے ساتھ رشتہ تلاش کریں",
    "Respectful aur safe rishta search. Guardian mode aur verification ke saath.": "احترام اور حفاظت کے ساتھ رشتہ کی تلاش۔ گارڈین موڈ اور تصدیق کے ساتھ۔",
    "In filters ke mutabiq koi profile nahi mili. Filters badal kar dekhein.": "ان فلٹرز کے مطابق کوئی پروفائل نہیں ملی۔ فلٹرز بدل کر دیکھیں۔",
    "Interest bhej diya gaya! 💚": "دلچسپی بھیج دی گئی! 💚",
    "Jab koi interest bheje": "جب کوئی دلچسپی بھیجے",
    "Yeh profile guardian mode mein hai. Aapka message guardian tak jayega.": "یہ پروفائل گارڈین موڈ میں ہے۔ آپ کا پیغام گارڈین تک جائے گا۔",
    "Aapka message seedha profile wale tak jayega.": "آپ کا پیغام سیدھا پروفائل والے تک جائے گا۔",
    "Apne aap ko request nahi bhej sakte": "خود کو درخواست نہیں بھیج سکتے",
    "Request nahi bheji ja saki": "درخواست نہیں بھیجی جا سکی",
    "Request id chahiye": "درخواست آئی ڈی درکار ہے",
    "Is request par pehle se action liya ja chuka hai": "اس درخواست پر پہلے ہی کارروائی ہو چکی ہے",
    "Apne baare mein chand satrein": "اپنے بارے میں چند سطریں",
    "Apne baare mein likhein — personality, hobbies, lifestyle...": "اپنے بارے میں لکھیں — شخصیت، مشاغل، طرزِ زندگی...",
    "Qubool hai": "قبول ہے",
    "Job Post Karein": "نوکری پوسٹ کریں",
    "Job chunein": "نوکری منتخب کریں",
    "Job id zaroori hai": "نوکری آئی ڈی ضروری ہے",
    "Job post nahi ho saki": "نوکری پوسٹ نہیں ہو سکی",
    "Job post karne ke liye pehle business profile banayein": "نوکری پوسٹ کرنے کے لیے پہلے بزنس پروفائل بنائیں",
    "Job ki mukammal tafseel likhein...": "نوکری کی مکمل تفصیل لکھیں...",
    "Job title ya company dhundein...": "نوکری کا عنوان یا کمپنی تلاش کریں...",
    "Abhi koi job nahi hai. Business owners job post kar sakte hain.": "ابھی کوئی نوکری نہیں ہے۔ بزنس مالکان نوکری پوسٹ کر سکتے ہیں۔",
    "Application nahi bheji ja saki": "درخواست نہیں بھیجی جا سکی",
    "Aap is job ke liye pehle se apply kar chuke hain": "آپ اس نوکری کے لیے پہلے ہی درخواست دے چکے ہیں",
    "Pehle apna job profile banayein (Profile > Job Profile)": "پہلے اپنا جاب پروفائل بنائیں (پروفائل > جاب پروفائل)",
    "Headline likhein (e.g. Software Engineer)": "ہیڈ لائن لکھیں (مثلاً سافٹ ویئر انجینئر)",
    "Apna tajurba share karein...": "اپنا تجربہ شیئر کریں...",
    "Cover letter — apne baare mein aur is job ke liye kyun apply kar rahe hain...": "کور لیٹر — اپنے بارے میں اور اس نوکری کے لیے کیوں درخواست دے رہے ہیں...",
    "Family businesses ki jobs. Apni community ke logon ke saath kaam karein.": "فیملی بزنسز کی نوکریاں۔ اپنی کمیونٹی کے لوگوں کے ساتھ کام کریں۔",
    "Apne business ke liye job post karein (Business profile zaroori hai)": "اپنے بزنس کے لیے نوکری پوسٹ کریں (بزنس پروفائل ضروری ہے)",
    "Business Register Karein": "بزنس رجسٹر کریں",
    "Business dhundein...": "بزنس تلاش کریں...",
    "Business id zaroori hai": "بزنس آئی ڈی ضروری ہے",
    "Business ke baare mein likhein...": "بزنس کے بارے میں لکھیں...",
    "Business register ho gaya! 🎉": "بزنس رجسٹر ہو گیا! 🎉",
    "Business register nahi ho saka": "بزنس رجسٹر نہیں ہو سکا",
    "Business deactivate ho gaya": "بزنس غیر فعال ہو گیا",
    "Aap ke paas pehle se aik business hai. Edit karein ya purana delete karein.": "آپ کے پاس پہلے سے ایک بزنس ہے۔ ترمیم کریں یا پرانا ڈیلیٹ کریں۔",
    "Abhi koi business listed nahi hai. Pehla business register karein!": "ابھی کوئی بزنس درج نہیں ہے۔ پہلا بزنس رجسٹر کریں!",
    "Family businesses discover karein": "فیملی بزنسز دریافت کریں",
    "Family-owned businesses discover karein aur reviews dein.": "فیملی بزنسز دریافت کریں اور جائزے دیں۔",
    "Review submit nahi ho saki": "جائزہ جمع نہیں ہو سکا",
    "Directory ke tamam businesses": "ڈائریکٹری کے تمام بزنسز",
    "Filters Clear Karein": "فلٹرز صاف کریں",
    "Memory Add Karein": "یاد شامل کریں",
    "Memory Banayein": "یاد بنائیں",
    "Nayi Memory Banayein": "نئی یاد بنائیں",
    "Memory mehfooz ho gayi! 📸": "یاد محفوظ ہو گئی! 📸",
    "Memory save nahi ho saki": "یاد محفوظ نہیں ہو سکی",
    "Abhi koi memory nahi hai. Apni pehli memory banayein!": "ابھی کوئی یاد نہیں ہے۔ اپنی پہلی یاد بنائیں!",
    "Yaadein mehfooz karein — photos, videos aur kahaniyan aik jagah.": "یادیں محفوظ کریں — تصاویر، ویڈیوز اور کہانیاں ایک جگہ۔",
    "Apni yaadein mehfooz karein": "اپنی یادیں محفوظ کریں",
    "Yaadein share karein, jobs dhundein, aur apna khandaan barhayein.": "یادیں شیئر کریں، نوکریاں ڈھونڈیں، اور اپنا خاندان بڑھائیں۔",
    "Is lamhe ki kahani likhein...": "اس لمحے کی کہانی لکھیں...",
    "Upload Karein": "اپ لوڈ کریں",
    "Photo Add Karein": "تصویر شامل کریں",
    "Photo upload nahi ho saki": "تصویر اپ لوڈ نہیں ہو سکی",
    "Ziada se ziada 5 photos upload kar sakte hain": "زیادہ سے زیادہ 5 تصاویر اپ لوڈ کر سکتے ہیں",
    "Image choose karne ke liye click karein (max 5MB)": "تصویر منتخب کرنے کے لیے کلک کریں (زیادہ سے زیادہ 5MB)",
    "Yahan click karein ya file drag karein (photos, videos, documents)": "یہاں کلک کریں یا فائل ڈریگ کریں (تصاویر، ویڈیوز، دستاویزات)",
    "File chunein": "فائل منتخب کریں",
    "File valid nahi hai": "فائل درست نہیں ہے",
    "Koi media nahi hai. Upload karein!": "کوئی میڈیا نہیں ہے۔ اپ لوڈ کریں!",
    "Media ids zaroori hain": "میڈیا آئی ڈیز ضروری ہیں",
    "Apni photos, videos aur documents yahan mehfooz karein": "اپنی تصاویر، ویڈیوز اور دستاویزات یہاں محفوظ کریں",
    "Aapki tamam files aik jagah": "آپ کی تمام فائلیں ایک جگہ",
    "Files search karein...": "فائلیں تلاش کریں...",
    "Photos load ho rahi hain...": "تصاویر لوڈ ہو رہی ہیں...",
    "Aapki tamam updates": "آپ کی تمام اپ ڈیٹس",
    "Read Mark Karein": "پڑھا ہوا نشان زد کریں",
    "Unread Mark Karein": "غیر پڑھا نشان زد کریں",
    "Yeh profile fake ya inappropriate lagti hai": "یہ پروفائل جعلی یا نامناسب لگتی ہے",
    "Yeh user inappropriate content ya behavior mein mulawwis lagta hai": "یہ صارف نامناسب مواد یا رویے میں ملوث لگتا ہے",
    "Kis bare mein baat karni hai?": "کس بارے میں بات کرنی ہے؟",
    "Wajah kam az kam 10 characters mein likhein": "وجہ کم از کم 10 حروف میں لکھیں",
    "Aap is user ko pehle se report kar chuke hain": "آپ اس صارف کو پہلے ہی رپورٹ کر چکے ہیں",
    "Apne aap ko report nahi kar sakte": "خود کو رپورٹ نہیں کر سکتے",
    "Report nahi ho saki": "رپورٹ نہیں ہو سکی",
    "Report id zaroori hai": "رپورٹ آئی ڈی ضروری ہے",
    "Report resolve karein": "رپورٹ حل کریں",
    "Report dismiss karein": "رپورٹ مسترد کریں",
    "Bar bar aisi shikayat par account ban ho sakta hai.": "بار بار ایسی شکایت پر اکاؤنٹ بند ہو سکتا ہے۔",
    "Report status update par": "رپورٹ کی صورتحال اپ ڈیٹ ہونے پر",
    "Ban ki wajah likhein...": "پابندی کی وجہ لکھیں...",
    "User ko ban karein": "صارف کو بند کریں",
    "Admin access zaroori hai": "ایڈمن رسائی ضروری ہے",
    "Users load nahi ho sake": "صارفین لوڈ نہیں ہو سکے",
    "User delete ho gaya": "صارف ڈیلیٹ ہو گیا",
    "Aap apne aap ko ban nahi kar sakte": "آپ خود کو بند نہیں کر سکتے",
    "Aap apne aap ko delete nahi kar sakte": "آپ خود کو ڈیلیٹ نہیں کر سکتے",
    "Role chunein": "کردار منتخب کریں",
    "User chunein": "صارف منتخب کریں",
    "Export fail ho gaya": "ایکسپورٹ ناکام ہو گیا",
    "Profile chunein": "پروفائل منتخب کریں",
    "Profile id zaroori hai": "پروفائل آئی ڈی ضروری ہے",
    "Entity aur id zaroori hain": "اندراج اور آئی ڈی ضروری ہیں",
    "Naye user ko account banane par": "نئے صارف کے اکاؤنٹ بننے پر",
    "2FA code ghalat hai": "2FA کوڈ غلط ہے",
    "2FA disable ho gaya": "2FA غیر فعال ہو گیا",
    "2FA disable nahi ho saka": "2FA غیر فعال نہیں ہو سکا",
    "2FA enabled ho gaya! 🔐": "2FA فعال ہو گیا! 🔐",
    "2FA enabled ho gaya!": "2FA فعال ہو گیا!",
    "2FA enabled nahi hai": "2FA فعال نہیں ہے",
    "2FA pehle se enabled hai": "2FA پہلے سے فعال ہے",
    "2FA setup start nahi ho saka": "2FA سیٹ اپ شروع نہیں ہو سکا",
    "2FA verify nahi ho saka": "2FA تصدیق نہیں ہو سکی",
    "6 digit ka OTP likhein": "6 ہندسوں کا OTP لکھیں",
    "6 digits ka code likhein": "6 ہندسوں کا کوڈ لکھیں",
    "Code likhein": "کوڈ لکھیں",
    "Code ghalat hai. Dobara koshish karein": "کوڈ غلط ہے۔ دوبارہ کوشش کریں",
    "Code ghalat hai": "کوڈ غلط ہے",
    "OTP 6 digits ka hota hai": "OTP 6 ہندسوں کا ہوتا ہے",
    "OTP aapke naye email par bhej diya gaya hai (10 minute valid)": "OTP آپ کی نئی ای میل پر بھیج دیا گیا ہے (10 منٹ تک درست)",
    "OTP aapke registered email par bhej diya gaya hai (10 minute valid)": "OTP آپ کی رجسٹرڈ ای میل پر بھیج دیا گیا ہے (10 منٹ تک درست)",
    "OTP bhej diya gaya hai": "OTP بھیج دیا گیا ہے",
    "OTP expire ho gaya hai. Naya OTP lein": "OTP کی مدت ختم ہو گئی ہے۔ نیا OTP لیں",
    "OTP ghalat hai": "OTP غلط ہے",
    "OTP nahi bheja ja saka": "OTP نہیں بھیجا جا سکا",
    "Ghalat OTP. Dobara check karein": "غلط OTP۔ دوبارہ چیک کریں",
    "Email badal gaya!": "ای میل بدل گیا!",
    "Phone number badal gaya!": "فون نمبر بدل گیا!",
    "Naya email likhein": "نیا ای میل لکھیں",
    "Naya phone number likhein": "نیا فون نمبر لکھیں",
    "Aapke account par koi email registered nahi hai": "آپ کے اکاؤنٹ پر کوئی ای میل رجسٹرڈ نہیں ہے",
    "Kids Mode ON! Maze karo! 🎈": "کڈز موڈ آن! مزے کرو! 🎈",
    "Quiz Shuru Karein": "کوئز شروع کریں",
    "Photo Quiz! Apni family ki yaadein pehchano 📸": "فوٹو کوئز! اپنی فیملی کی یادیں پہچانو 📸",
    "Ye photo kis yaad (memory) ki hai?": "یہ تصویر کس یاد کی ہے؟",
    "Yeh kaun hain? (Photo mein jo dikh rahe hain)": "یہ کون ہیں؟ (تصویر میں جو نظر آ رہے ہیں)",
    "Bachon ki Eid par kya milta hai?": "بچوں کو عید پر کیا ملتا ہے؟",
    "Ammi ki Ammi aapki kya lagti hain?": "امی کی امی آپ کی کیا لگتی ہیں؟",
    "Aapka rishta kya hai? Dada Abu ke bhai se": "آپ کا رشتہ کیا ہے؟ دادا ابو کے بھائی سے",
    "Nikkah ki rasam mein kya hota hai?": "نکاح کی رسم میں کیا ہوتا ہے؟",
    "Eid Milan Party kab hui thi?": "عید ملن پارٹی کب ہوئی تھی؟",
    "Ghalat! -5 points": "غلط! -5 پوائنٹس",
    "Dawa ka naam likhein": "دوا کا نام لکھیں",
    "Dawa ka reminder save ho gaya!": "دوا کا ریمائنڈر محفوظ ہو گیا!",
    "Emergency number par call ja rahi hai... 📞": "ایمرجنسی نمبر پر کال جا رہی ہے... 📞",
    "Buzurg Mode se record kiya gaya voice note": "بزرگ موڈ سے ریکارڈ کیا گیا وائس نوٹ",
    "Buzurg mode ki wajah se meri Ammi ab khud video calls karti hain. Medicine reminder feature bohat kaam aaya. Allah khush rakhe team ko.": "بزرگ موڈ کی وجہ سے میری امی اب خود ویڈیو کالز کرتی ہیں۔ میڈیسن ریمائنڈر فیچر بہت کام آیا۔ اللہ خوش رکھے ٹیم کو۔",
    "Recording shuru... Rokne ke liye dobara button dabayein": "ریکارڈنگ شروع... روکنے کے لیے دوبارہ بٹن دبائیں",
    "Voice note save ho gaya! Memories mein dekhein 🎙️": "وائس نوٹ محفوظ ہو گیا! یادوں میں دیکھیں 🎙️",
    "Voice note save karne mein masla aa gaya": "وائس نوٹ محفوظ کرنے میں مسئلہ آ گیا",
    "Voice note save nahi hua": "وائس نوٹ محفوظ نہیں ہوا",
    "Microphone ki ijazat nahi mili. Browser settings check karein.": "مائیکروفون کی اجازت نہیں ملی۔ براؤزر سیٹنگز چیک کریں۔",
    "Family ko bataya gaya: Main theek hoon! 💚": "فیملی کو بتا دیا گیا: میں ٹھیک ہوں! 💚",
    "Bade buzurgon ke liye simple UI, video calls aur medicine reminders.": "بڑے بزرگوں کے لیے سادہ UI، ویڈیو کالز اور میڈیسن ریمائنڈرز۔",
    "Subject likhein": "موضوع لکھیں",
    "Message Bhejein": "پیغام بھیجیں",
    "Message bhej diya gaya! Hum jald raabta karein gay.": "پیغام بھیج دیا گیا! ہم جلد رابطہ کریں گے۔",
    "Message bhej diya gaya!": "پیغام بھیج دیا گیا!",
    "Message delete ho gaya": "پیغام ڈیلیٹ ہو گیا",
    "Message id zaroori hai": "پیغام آئی ڈی ضروری ہے",
    "Message 1000 characters se zyada nahi ho sakta": "پیغام 1000 حروف سے زیادہ نہیں ہو سکتا",
    "Apna message yahan likhein...": "اپنا پیغام یہاں لکھیں...",
    "Bio 500 characters se zyada nahi ho sakta": "تعارف 500 حروف سے زیادہ نہیں ہو سکتا",
    "Apna taaruf aur family ke baare mein mukhtasar likhein...": "اپنا تعارف اور فیملی کے بارے میں مختصر لکھیں...",
    "Apne khandaan ke baare mein likhein...": "اپنے خاندان کے بارے میں لکھیں...",
    "Umar 80 se zyada nahi ho sakti": "عمر 80 سے زیادہ نہیں ہو سکتی",
    "Aapka data aapka hai. End-to-end security ke saath.": "آپ کا ڈیٹا آپ کا ہے۔ اینڈ ٹو اینڈ سیکیورٹی کے ساتھ۔",
    "Account delete ho gaya. Allah Hafiz! 👋": "اکاؤنٹ ڈیلیٹ ہو گیا۔ اللہ حافظ! 👋",
    "Account delete ho gaya": "اکاؤنٹ ڈیلیٹ ہو گیا",
    "Account delete nahi ho saka": "اکاؤنٹ ڈیلیٹ نہیں ہو سکا",
    "Humara family business ab directory par listed hai aur community ke logon se 3 naye orders mile hain. Jobs post karna bhi bohat aasan hai.": "ہمارا فیملی بزنس اب ڈائریکٹری میں درج ہے اور کمیونٹی کے لوگوں سے 3 نئے آرڈرز ملے ہیں۔ نوکریاں پوسٹ کرنا بھی بہت آسان ہے۔",
    "Khush aamdeed Digital Family Tree mein!": "ڈیجیٹل فیملی ٹری میں خوش آمدید!",
    "Khush aamdeed!": "خوش آمدید!",
    "Family Picnic aa rahi hai": "فیملی پکنک آنے والی ہے",
    "7 din baad hai. RSVP karein!": "7 دن بعد ہے۔ RSVP کریں!",
    "Rishta request bheji gayi hai": "رشتہ کی درخواست بھیجی گئی ہے",
    "Rishta request accept ho gayi hai": "رشتہ کی درخواست قبول ہو گئی ہے",
    "Naya user account bana": "نئے صارف نے اکاؤنٹ بنایا",
    "Ne account banaya": "نے اکاؤنٹ بنایا",
    "Member ne new event banaya": "ممبر نے نیا ایونٹ بنایا",
    "User ne event banaya": "صارف نے ایونٹ بنایا",
    "Member ne rishta profile banayi": "ممبر نے رشتہ پروفائل بنایا",
    "User ne rishta profile banaya": "صارف نے رشتہ پروفائل بنایا",
    "Member ne job apply kiya": "ممبر نے نوکری کے لیے درخواست دی",
    "User ne job apply kiya": "صارف نے نوکری کے لیے درخواست دی",
    "Member ne business register kiya": "ممبر نے بزنس رجسٹر کیا",
    "User ne business register kiya": "صارف نے بزنس رجسٹر کیا",
    "Mehndi ki rasam": "مہندی کی رسم",
    "Shaadi ki rasam": "شادی کی رسم",
    "Barat ki rasam": "بارات کی رسم",
    "Family picnic — Jallo Park, Lahore": "فیملی پکنک — جالو پارک، لاہور",
    "Dost aur khandaan ke saath picnic": "دوستوں اور خاندان کے ساتھ پکنک",
    "Bachpan ki yaadein": "بچپن کی یادیں",
    "Bachpan ki pyari yaadein": "بچپن کی پیاری یادیں",
    "Swat ka safar": "سوات کا سفر",
    "Family trip to Swat": "سوات کا فیملی ٹرپ",
    "Eid ki khushiyan": "عید کی خوشیاں",
    "Eid ki namaz ke baad family ke saath": "عید کی نماز کے بعد فیملی کے ساتھ",
    "Community delete karne se pehle is ke clans delete karne honge.": "کمیونٹی ڈیلیٹ کرنے سے پہلے اس کے کلانز ڈیلیٹ کرنے ہوں گے۔",
    "Family ko invite karne ke liye event details bharein": "فیملی کو مدعو کرنے کے لیے ایونٹ کی تفصیلات بھریں",
    "Family info add karna": "فیملی معلومات شامل کریں",
    "Photos upload karna": "تصاویر اپ لوڈ کریں",
    "Puri family ki Eid Milan party. Sab log zaroor aayein! Khana, mithaai aur dher sari batein.": "پوری فیملی کی عید ملن پارٹی۔ سب لوگ ضرور آئیں! کھانا، مٹھائی اور ڈھیر ساری باتیں۔",
    "1998 ki Eid — sab cousins aik saath. Kya din thay!": "1998 کی عید — سب کزنز ایک ساتھ۔ کیا دن تھے!",
    "Abbu ki barsi par Quran khawani. Isha ke baad dua hogi.": "ابو کی برسی پر قرآن خوانی۔ عشاء کے بعد دعا ہوگی۔",
    "Alhamdulillah, naya business shuru ho raha hai. Dua ke liye tashreef layein.": "الحمدللہ، نیا بزنس شروع ہو رہا ہے۔ دعا کے لیے تشریف لائیں۔",
    "Allah ke fazal se Ahmed ki shadi. Nikkah ki rasam, dua ki darkhwast hai.": "اللہ کے فضل سے احمد کی شادی۔ نکاح کی رسم، دعا کی درخواست ہے۔",
    "Hamein apni textile division ke liye tajurba kaar Sales Manager chahiye. Candidate ke paas minimum 5 saal ka tajurba hona chahiye.": "ہمیں اپنی ٹیکسٹائل ڈویژن کے لیے تجربہ کار سیلز مینیجر چاہیے۔ امیدوار کے پاس کم از کم 5 سال کا تجربہ ہونا چاہیے۔",
    "Privacy policy yahan likhein.": "پرائیویسی پالیسی یہاں لکھیں۔",
    "Terms of service yahan likhein.": "شرائطِ استعمال یہاں لکھیں۔",
    "Monthly family picnic. Bachon ke liye games aur cricket match ka intizam hoga.": "ماہانہ فیملی پکنک۔ بچوں کے لیے گیمز اور کرکٹ میچ کا انتظام ہوگا۔",
    "Khandaan ki Eid Milan Party": "خاندان کی عید ملن پارٹی",
    "Family Picnic — Jallo Park": "فیملی پکنک — جالو پارک",
    "Bachpan ki Eid": "بچپن کی عید",
    "Teacher aur parhai ki shauqeen 📚": "ٹیچر اور پڑھائی کی شوقین 📚",
    "OTP aapke registered email par jayega": "OTP آپ کی رجسٹرڈ ای میل پر جائے گا",
    "Maujuda phone": "موجودہ فون",
    "Maujuda email": "موجودہ ای میل",
    "Chacha": "چچا",}

QUOTED = {
    "Sab": "تمام",
    "Rishta": "رشتہ",
    "Khandaan": "خاندان",
}

def process_file(path):
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    original = content
    for k in sorted(RAW, key=len, reverse=True):
        if k in content:
            content = content.replace(k, RAW[k])
    for k, v in QUOTED.items():
        content = re.sub(r'"' + re.escape(k) + r'"', '"' + v + '"', content)
    if content != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    return False

if __name__ == "__main__":
    count = 0
    for root, dirs, files in os.walk("src"):
        dirs[:] = [d for d in dirs if d not in (".next", "node_modules")]
        for name in files:
            if name.endswith((".tsx", ".ts")):
                if process_file(os.path.join(root, name)):
                    count += 1
    if process_file("prisma/seed.ts"):
        count += 1
    print(f"Updated {count} files")
